# Training parameters
num_epochs: !!int 1
model_name: !!str x3d_m
data_filename: !!str data/ObjectRecon_SWIN3D_2016-2023_inference_predictions_with_df_metadata_and_report_1000.csv
mean: [120.905205, 120.905205, 120.905205]
std: [40.97189, 40.97189, 40.97189]
output_dir: !!str "outputs"
root: !!str "."
datapoint_loc_label: !!str FileName
binary_threshold: !!float 0.5
use_amp: !!bool True
frames: !!int 72
device: !!str cuda
period: !!int 2
pretrained: !!bool True
seed: !!int 0
optimizer: !!str SGD
weight_decay: !!float 0.00000049811877376642
num_workers: !!int 8
batch_size: !!int 4
lr: !!float 0.0007008364943470314
label_smoothing: !!null null
label_smoothing_value: !!null null
class_weights: !!null null

# Loss and task configuration
loss: !!str multi_head  # Use multi-head loss for multiple classification tasks
task: !!str classification  # Indicates this is a multi-head classification model

# Label mappings
labels_map:
  contrast_agent:
    "yes": !!int 1
    "no": !!int 0
  main_structure:
    Left Coronary: !!int 0
    Right Coronary: !!int 1
    Graft: !!int 2
    Catheter: !!int 3
    Femoral: !!int 4
  stent_presence:
    present: !!int 1
    absent: !!int 0

# Head structure configuration
head_structure:
  contrast_agent: !!int 1    # Binary classification (0 or 1)
  main_structure: !!int 5    # Multi-class classification (5 classes)
  stent_presence: !!int 1    # Binary classification (0 or 1)

# Loss structure configuration
loss_structure:
  contrast_agent: !!str bce_logit
  main_structure: !!str ce
  stent_presence: !!str bce_logit

# Head weights configuration
head_weights:
  contrast_agent: !!float 1.0
  main_structure: !!float 1.0
  stent_presence: !!float 1.0

# Scheduler configuration
scheduler_type: !!str step
factor: !!float 0.3
patience: !!int 7
threshold: !!float 0.01
lr_step_period: !!int 15
run_test: !!bool true
tag: !!str filtered_deepRV_multihead_72_16_0.007
project: !!str test_multi_head_classification
entity: !!str mhi_ai
resume: !!bool false 
rand_augment: !!bool true
resize: !!int 256
apply_mask: !!bool false
view_count: !!null null
save_best: !!str loss

# Wandb
early_terminate:
  type: !!str hyperband
  min_iter: !!int 3

# Metrics control
metrics_control:
  optim_thresh: !!str g_mean
  plot_pred_distribution: !!bool true
  plot_metrics_moving_thresh: !!bool true
  n_bootstrap: !!int 100
  q_bootstrap: !!float 0.05

transforms: !!null null