# MViT v2 S with 3D RoPE Configuration
# Training parameters
num_epochs: !!int 20
model_name: !!str mvit_v2_s
data_filename: !!str /media/data1/datasets/CathEF/CathEF_MHI_UCSF_2016-to-july-2022-and-2023-08-30-post-CathEF_alpha_filtered_30days.csv
output_dir: !!str "outputs"
root: !!str "."
datapoint_loc_label: !!str FileName
label_loc_label: !!null null  # Not used for single-head regression
binary_threshold: !!float 40.0  # Threshold for LVEF metrics
use_amp: !!bool True
target_label: Value  # Continuous LVEF value column
resume: !!bool false  # Required field

# MViT specific parameters
frames: !!int 16  # MViT requires 16 frames
resize: !!int 224  # MViT standard input size
device: !!str cuda
period: !!int 2
pretrained: !!bool True
seed: !!int 0

# Optimizer configuration
optimizer: !!str AdamW
weight_decay: !!float 0.05
num_workers: !!int 8
batch_size: !!int 2  # Smaller batch size for MViT
lr: !!float 0.00002  # Lower learning rate for stability with RoPE

# 3D RoPE Configuration
use_rope: !!bool true
rope_base: !!float 10000.0
rope_temporal_scale: !!float 1.0
rope_normalize_mode: !!str separate

# Gradual unfreezing schedule for fine-tuning with RoPE
video_freeze_schedule: !!str cosine
video_freeze_start: !!float 0.95  # Start with 95% frozen
video_freeze_end: !!float 0.0     # End fully trainable
video_freeze_warmup_epochs: !!int 10

# Loss and task configuration
loss: !!str mse  # MSE loss for regression (L2 loss)
task: !!str regression  # Regression task for continuous LVEF values
num_classes: !!int 1  # Single output for regression

# Learning rate scheduler
scheduler: !!str cosine
warmup_epochs: !!int 5
min_lr: !!float 0.000001

# Augmentation parameters
augment: !!bool true
crop_size: !!int 224
horizontal_flip_prob: !!float 0.5
vertical_flip_prob: !!float 0.0
rotation_degrees: !!int 10
brightness: !!float 0.2
contrast: !!float 0.2
saturation: !!float 0.2
hue: !!float 0.1

# Validation parameters
val_split: !!float 0.2
eval_every_n_epochs: !!int 1
save_best_model: !!bool true
early_stopping_patience: !!int 5

# Logging
wandb_project: !!str "orion-mvit-rope"
wandb_entity: !!null mhi_ai
log_interval: !!int 10
save_checkpoint_every_n_epochs: !!int 5

# Mixed precision and gradient accumulation
gradient_accumulation_steps: !!int 4
gradient_clip_val: !!float 1.0

# Label smoothing (optional)
label_smoothing: !!null null
label_smoothing_value: !!null null
class_weights: !!null null