training_mode: "contrastive"
model_name: "mvit_base_16x4"
output_dim: 512
temperature: 0.07
weight_decay: 0.01
use_amp: true

# Training parameters
batch_size: 32
num_epochs: 60
learning_rate: 1e-4
num_workers: 4
seed: 42

# Video parameters
frames: 16
resize: 224
crop: 224
mean: [0.45, 0.45, 0.45]
std: [0.225, 0.225, 0.225]

# Model saving
save_model: true
output_dir: "models/contrastive"

# Wandb logging
wandb:
  project: "orion-contrastive"
  entity: "your-entity"
  tags: ["contrastive", "mvit", "pubmedbert"]