program:
  ../orion/utils/video_training_and_eval.py
name: "1_CathEF_UCSF_MHI_2021_Retrain_15_fps_ddp"
method: "bayes" # grid, random
metric:
  name: "best_val_loss"
  goal: "minimize"
parameters:
  model_name:
    values: ["swin3d_s"]
  lr:
    distribution: "uniform"
    min: 1e-8
    max: 2e-5
  rand_augment:
    values: [True, False]
  scheduler_type:
    values: ["plateau", "step", "cosine_warm_restart"]
  optimizer:
    values: ["AdamW", "RAdam"]
  weight_decay:
    min: 0.0  # explicitly a float
    max: 0.00001  # explicitly a float, equivalent to 1e-3
  patience:
    min: 5
    max: 15
  factor:
    values: [0.3, 0.5]
early_terminate:
  type: hyperband
  min_iter: 3    
command:
  - /volume/Orion/notebooks/config/runner.sh
  - ${program}
  - "config/config_regression_swin3d.yaml"
  - ${args}