# config.yaml

## TRAINING PARAMETERS
dataset_path: "/media/data1/ravram/CathEF_Retrain/train_val_test_LCA_REGRESSION_with_MHI_2016-to-July-2022_data_NAS_path_alpha.csv"
separator: "α"                            # Options: "," , ";", "α", "β", "γ", "δ", "ε", "ζ", "η", "θ", "ι", "κ", "λ", "μ", "ν", "ξ", "ο", "π", "ρ", "σ", "τ", "υ", "φ", "χ", "ψ", "ω".........
dataset_origin: "MHI_CLIPPED"             # Options: "TESTCASE", "MHI", "UCSF", "BOTH", "UCSF_CLIPPED", "MHI_CLIPPED" --> "TESTCASE": OVERIDES the other parameters and test the code on training the network for white/black video classification
fps: 0                                    # Options: 0, 15 --> 0: for all FPS
how_many: 0                               # Options: 0, 100, 200, 300, 400, 500 --> 0: for all data
batch_size: 20                            # Options: 8, 16, 32, 64....
num_workers: 8                            # Options: 4, 8, 16, 32....
num_epochs: 100                           # Options: 100, 200, 300, 400, 500....
threshold: 0.4                            # Options: [0:1] --> 0.5 for binary classification
in_memory: false                          # Options: true, false
use_wandb: true                           # Options: true, false
model_name: "x3d_m"                       # Options: "x3d_xs", "x3d_s", "x3d_m"
pretrained: true                          # Options: true, false
problem_type: "regression"                # Options: "regression", "classification"
classes: 1                                # Options: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 .... --> 1 for regression or binary classification
criterion_name: "SmoothL1Loss"            # Options: "SmoothL1Loss", "MSELoss", "L1Loss"
optimizer_name: "RAdam"                   # Options: "Adam", "AdamW", "SGD"
learning_rate: 0.0001                     # Options: 0.00001, 0.0001, 0.001, 0.01, 0.1 --> More stable around 0.0001
label_column: "Value"                     # Options: ....
filename_column: "FileName"               # Options: ....
split_column: "Split"                     # Options: ....
fps_column: "FPS"                         # Options: ....
label_normalized: false                   # Options: true, false
modulo_5: false                           # Options: true, false
num_frames: 48                            # Options: 32,48,72 ....
frames_size: 256                          # Options: 182, 224, 256 ....
lr_scheduler:                             # Options: "ReduceLROnPlateau"
  factor: 0.1
  patience: 10
  verbose: true


## INFERENCE PARAMETERS
INFERENCE_DATASET_PATH: "/media/data1/ravram/CathEF_Retrain/train_val_test_LCA_REGRESSION_with_MHI_2016-to-July-2022_data_NAS_path_alpha.csv"
INFERENCE_SEPARATOR: "α"
INFERENCE_DATASET_ORIGIN: "MHI"
INFERENCE_MODEL_PATH: "/volume/Orion/OrionV2/experiments/x3d_m_MHI_CLIPPED_0_RAdam_0.0001_SmoothL1Loss_regression_True_48_20_d9se5s"
INFERENCE_HOW_MANY: 0
INFERENCE_FPS: 0
INFERENCE_THRESHOLD: 0.4
INFERENCE_BATCH_SIZE: 8
INFERENCE_NUM_WORKERS: 8
INFERENCE_MODEL_NAME: "x3d_m"
INFERENCE_PROBLEM_TYPE: "regression"
INFERENCE_CLASSES: 1
INFERENCE_LABEL_COLUMN: "Value"
INFERENCE_FILENAME_COLUMN: "FileName"
INFERENCE_SPLIT_COLUMN: "Split"
INFERENCE_FPS_COLUMN: "FPS"
INFERENCE_LABEL_NORMALIZED: false
INFERENCE_MODULO_5: false
INFERENCE_NUM_FRAMES: 48
INFERENCE_FRAMES_SIZE: 256
INFERENCE_IN_MEMORY: false
INFERENCE_STRIDE: 48

